[package]
name = "aster"
version = "1.1.0"
cairo-version = ">=2.13.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "./migrate"

[dependencies]
starknet = ">=2.13.1"
dojo = "=1.8.0"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
nft_combo = { git = "https://github.com/underware-gg/cairo-nft-combo", tag = "v1.2.0" }

[dev-dependencies]
cairo_test = ">=2.13.1"
dojo_cairo_test = "=1.8.0"

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
  "dojo::world::world_contract::world",
]

# debug contract size issues
# needed by `sozo build --stats.by-tag`
# casm = true


#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.sepolia]
[profile.mainnet]
