#
# torii config for profile [mainnet]
#
world_address = "0x7774946aab21c0b2b2484aa9a6f03bb64fd33550bb2cc8b22d46922b49af17c"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[events]
raw = true

[sql]
historical = []

[indexing]
pending = true
transactions = false
world_block = 2345258    # Astraea mainnet deployment block
contracts = [
  "erc721:0x0191e5a4490bf246a9acd76d17bd2e3eb208eb7f5c0795dc4848f338b2e27277", # Astraea
]
