#
# torii config for profile [sepolia]
#
world_address = "0x07774946aab21c0b2b2484aa9a6f03bb64fd33550bb2cc8b22d46922b49af17c"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[events]
raw = true

[sql]
historical = []

[indexing]
pending = true
transactions = false
world_block = 2148277    # Astraea sepolia deployment block
contracts = [
  "erc721:0x05bb54b047419c975c3be4e2cd5ad3df6084f5df96008182c214a78bd694f61e", # Astraea
]
